site_name: anystore
site_url: https://docs.investigraph.dev/lib/anystore
repo_url: https://github.com/dataresearchcenter/anystore
nav:
  - Intro: index.md
  - quickstart.md
  - Documentation:
    - overview.md
    - Basic usage: usage.md
    - Use as blob storage: storage.md
    - Use as cache backend: cache.md
    - configuration.md
    - serialization.md
  - Reference:
    - CLI:
      - anystore.cli: reference/cli.md
    - I/O:
      - anystore.io: reference/io.md
      - anystore.decorators: reference/decorators.md
    - Store:
      - anystore.store: reference/store.md
      - anystore.store.resource: reference/resource.md
    - Interfaces:
      - anystore.interface.tags: reference/tags.md
      - anystore.interface.lock: reference/lock.md
      - anystore.interface.queue: reference/queue.md
    - Model:
      - anystore.model: reference/model.md
    - Logic:
      - anystore.logic.serialize: reference/serialize.md
      - anystore.logic.virtual: reference/virtual.md
    - Utilities:
      - anystore.util: reference/util.md
      - anystore.settings: reference/settings.md
theme:
  name: material
  logo: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg
  favicon: https://cdn.investigativedata.org/style/logos/darc/favicon.ico
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      toggle:
        icon: lucide/sun
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/sun
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    - toc.follow
    - content.code.copy
extra_css:
  - https://dataresearchcenter.github.io/zensical-theme-darc/stylesheets/darc-zensical.css
extra:
  logo_light: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Pos.svg
  social:
    - icon: lucide/mail
      link: mailto:hi@dataresearchcenter.org
    - icon: lucide/globe
      link: https://dataresearchcenter.org
    - icon: simple/github
      link: https://github.com/dataresearchcenter/anystore
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/dataresearchcenter/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - autorefs
  - mkdocs-typer2:
      pretty: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: false
            show_object_full_path: false
